FROM mcr.microsoft.com/vscode/devcontainers/python:3.9

ENV PGHOST=localhost
ENV PGPASSWORD=password
ENV PGUSER=poffertjes_shop
ENV PGDATABASE=poffertjes_shop
ENV PGSCHEMA=public
ENV DBT_PROFILES_DIR=/workspaces/pytest-dbt-conventions/dbt_projects
ENV DBT_PROJECT_DIR=/workspaces/pytest-dbt-conventions/dbt_projects/poffertjes_shop